### ISSUE TITLE
Create Scooper Monobehavior

### ISSUE THREAD

**Issue by BFJDev** [jojods1125/FoodTruckVR#14]
Create a monobehavior that can be attached to the scooper. The scooper should be able to store on it an ingredient type so that it knows what type of ingredient it is holding. The scooper should also have a method on it that checks orientation. If turned upside down, dump what ingredient it is holding by spawning a 3D object that falls to the ground. Talk to Ben/Joseph if you have questions

**Comment by nbkehn** [comment]
Finished the scooper. It checks orientation through the update method. The ingredient filling is handled by the heater.
