### ISSUE TITLE
Give yourself a funny display name (IMPORTANT)

### ISSUE THREAD

**Issue by BFJDev** [jojods1125/FoodTruckVR#16]
In the GGJ2020 slack, set your display name to be "FirstName" + 'food word' + "LastName"

Failure to do so will see you removed from the project

**Comment by jojods1125** [comment]
All nicknames are in.

Alberto 'Drumstick' Carrillo
Joseph 'Butterbeer' Dasilva
Nico 'Nacho' Kehn
Ben 'Spicy' Johnson
Blaine 'Krispy' Carrick
Jackson 'Brioche' Bostian
Karthik 'Grill Marks' Chandran
Mitchell 'Well' Dunning
