### ISSUE TITLE
Moving Highway Desync

### ISSUE THREAD

**Issue by thehappypretzel** [jojods1125/FoodTruckVR#19]
Since the highway and buildings move as a rigid body with physics, whenever the slosh happens it can sometimes affect the highway and become desynced with it's intended movement.

Perhaps prevent the rigid body from receiving force or only move it using velocity if that's possible.

**Comment by jojods1125** [comment]
You can lock the Rigidbody to one axis so it doesn't veer off course.

**Comment by thehappypretzel** [comment]
forgot to update this and already did that plus made it go the right way so we arent in britain anymore
